configuration: Release

branches:
  only:
    - master

before_build:
  - nuget restore src/Autofac.Extras.NLog.sln

build:
  project: src/Autofac.Extras.NLog.sln
  verbosity: minimal
  
test:
  assemblies:
    - '**\*.Tests.dll'
